CC = /usr/bin/g++
CFLAGS = -O2 -Wall -Iglui/include

# Build libglui from https://github.com/libglui/glui
# Last tested commit was: 093edc777c02118282910bdee59f8db1bd46a84d

LIBS =  -lglui_static -framework OpenGL -framework GLUT

traceview : traceview.cpp 
	$(CC) $(CFLAGS) traceview.cpp $(LIBS) -o traceview

clean :
	rm -f traceview
